name: Backup Firestore

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  PROJECT_ID: sweatnotes-sn
  BUCKET: gs://sweatnotes-sn-backups

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SWEATNOTES_BACKUP_SERVICE_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
